### ISSUE TITLE
No train.py and about the model

### ISSUE THREAD

**Issue by utkutpcgl** [tisbuet/Real-time-distortion-classification-in-Laparoscopic-videos#1]
Thanks for your work!

There is no train.py file in the repo and could tell us about the model architecture? What did you use to extract the features from the images?

**Comment by tisbuet** [comment]
We appreciate @utkutpcgl bringing this to our attention. Indeed, this is an ongoing research effort managed by my professor's students. However, older commits include the train.py script.
url: https://github.com/tisbuet/Real-time-distortion-classification-in-Laparoscopic-videos/blob/115b68910429323691fae658bdd598639e068b1b/train.py

**Comment by utkutpcgl** [comment]
Thank you, best wishes 👍
